In [1]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2['d']

6

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [20]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [32]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [33]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [35]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [36]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [38]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [39]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [40]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [41]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [42]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [43]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [44]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [47]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [48]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

AttributeError: 'list' object has no attribute 'astype'

In [49]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [50]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [51]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [52]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [53]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [54]:
index[1:]

Index(['b', 'c'], dtype='object')

In [55]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [56]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [57]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [58]:
obj2.index is labels

True

In [59]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [60]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [61]:
'Ohio' in frame3.columns

True

In [62]:
2003 in frame3.index

False

In [63]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [64]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [65]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [66]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [67]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [68]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [69]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [70]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [71]:
frame.loc[['a', 'b', 'c', 'd'], states]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [72]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [73]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [74]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [75]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [77]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [78]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [79]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [80]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [81]:
obj['b']

1.0

In [82]:
obj[1]

1.0

In [83]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [84]:
 obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [85]:
 obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [86]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [87]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [88]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [89]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [91]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [92]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [93]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [95]:
data[data < 5] = 0

In [96]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [98]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [99]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [100]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [101]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [102]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [103]:
ser = pd.Series(np.arange(3.))
ser
ser[-1]

KeyError: -1

In [104]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [105]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [106]:
ser.iloc[-1]

2.0

In [107]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [108]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [109]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [110]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [111]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [112]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde')
                   ,index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [113]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [114]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [115]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [116]:
df2

B
0  3
1  4

In [117]:
df1 -df2

A   B
0 NaN NaN
1 NaN NaN

In [118]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [119]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [120]:
df1 - df2

a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1 -1.0 -1.0 -1.0 -1.0 NaN
2 -2.0 -2.0 -2.0 -2.0 NaN
3  NaN  NaN  NaN  NaN NaN

In [121]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [122]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [123]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [124]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [125]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [126]:
arr[0]

array([0., 1., 2., 3.])

In [127]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [128]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [129]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [130]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [131]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [132]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [133]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [134]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [135]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.842198  1.319686  0.377730
Ohio    0.219503  1.757067  1.137815
Texas  -1.920713  0.264192  1.888165
Oregon -0.886657 -2.236233 -1.064428

In [136]:
np.abs(frame)

b         d         e
Utah    1.842198  1.319686  0.377730
Ohio    0.219503  1.757067  1.137815
Texas   1.920713  0.264192  1.888165
Oregon  0.886657  2.236233  1.064428

In [137]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.140216
d    3.993300
e    2.952593
dtype: float64

In [138]:
frame.apply(f, axis='columns')

Utah      3.161884
Ohio      1.537564
Texas     3.808878
Oregon    1.349576
dtype: float64

In [139]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.920713 -2.236233 -1.064428
max  0.219503  1.757067  1.888165

In [140]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -1.84   1.32   0.38
Ohio     0.22   1.76   1.14
Texas   -1.92   0.26   1.89
Oregon  -0.89  -2.24  -1.06

In [141]:
frame['e'].map(format)

Utah       0.38
Ohio       1.14
Texas      1.89
Oregon    -1.06
Name: e, dtype: object

In [142]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [143]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [144]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [145]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [146]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [147]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [148]:
obj = pd.Series([4, 7, -3, 2])

In [149]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [150]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [151]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [152]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [153]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [154]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [155]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [229]:
obj.rank(ascending=False, method='max')

0    4.0
1    9.0
2    1.0
3    9.0
4    9.0
5    6.0
6    6.0
7    4.0
8    4.0
dtype: float64

In [157]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [158]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [159]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [160]:
obj.index.is_unique

False

In [161]:
obj['a']

a    0
a    1
dtype: int64

In [162]:
obj['c']

4

In [163]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -1.785641  0.224694  0.181608
a -1.579096  0.212475 -2.535903
b  1.517893 -0.395180 -1.023228
b -0.634730 -0.858003 -0.509800

In [164]:
df.loc['b']

0         1         2
b  1.517893 -0.395180 -1.023228
b -0.634730 -0.858003 -0.509800

In [165]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [166]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [167]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [168]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [169]:
df.idxmax()

one    b
two    d
dtype: object

In [170]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [171]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [172]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [173]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [174]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-12-10  0.006588  0.014999  0.026426  0.002865
2018-12-11 -0.005719 -0.001981  0.009295  0.011736
2018-12-12  0.002787  0.002233  0.004512  0.011343
2018-12-13  0.010940 -0.003549  0.003392 -0.001673
2018-12-14 -0.032700 -0.007907 -0.031247 -0.017817

In [175]:
returns['MSFT'].corr(returns['IBM'])

0.47998272130248903

In [176]:
returns['MSFT'].cov(returns['IBM'])

8.428303601644135e-05

In [177]:
returns.MSFT.corr(returns.IBM)

0.47998272130248903

In [178]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.365602  0.433493  0.444700
IBM   0.365602  1.000000  0.479983  0.402698
MSFT  0.433493  0.479983  1.000000  0.527856
GOOG  0.444700  0.402698  0.527856  1.000000

In [179]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000263  0.000072  0.000101  0.000111
IBM   0.000072  0.000149  0.000084  0.000076
MSFT  0.000101  0.000084  0.000207  0.000117
GOOG  0.000111  0.000076  0.000117  0.000236

In [181]:
returns.corrwith(returns.IBM)

AAPL    0.365602
IBM     1.000000
MSFT    0.479983
GOOG    0.402698
dtype: float64

In [182]:
returns.corrwith(volume)

AAPL   -0.059076
IBM    -0.176339
MSFT   -0.086970
GOOG   -0.016010
dtype: float64

In [183]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [184]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [185]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [186]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
b    2
d    1
dtype: int64

In [187]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [188]:
mask = obj.isin(['b', 'c'])

In [189]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [190]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [191]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [192]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [193]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [227]:
### PROBLEM FOR CLASS
#2 google[google['Adj Close'] == google['Adj Close'].max()].index[0]
# or google['Adj Close'].idxmax()
#3 google[google['Adj Close'] == google['Adj Close'].min()].index[0]
#4 google['Adj Close'].mean()

In [283]:
#1 
google = web.get_data_yahoo('GOOG')
google

High          Low         Open        Close      Volume  \
Date                                                                         
2010-01-04   312.721039   310.103088   311.449310   311.349976   3937800.0   
2010-01-05   311.891449   308.761810   311.563568   309.978882   6048500.0   
2010-01-06   310.907837   301.220856   310.907837   302.164703   8009000.0   
2010-01-07   303.029083   294.410156   302.731018   295.130463  12912000.0   
2010-01-08   299.675903   292.651581   294.087250   299.064880   9509900.0   
2010-01-11   300.276978   295.100647   300.276978   298.612823  14519600.0   
2010-01-12   297.147339   292.100159   296.893982   293.332153   9769600.0   
2010-01-13   292.288940   285.095734   286.382355   291.648102  13077600.0   
2010-01-14   295.180145   289.521942   290.063416   293.019196   8535300.0   
2010-01-15   294.862213   287.152344   294.752930   288.126007  10939600.0   
2010-01-19   293.302338   286.283020   288.722137   291.911407   8689500.0   
2010-01-20   291.096710   285.786224   291.096710   288.329681   6543600.0   
2010-01-21   291.513977   284.276062   289.834900   289.606384  12697400.0   
2010-01-22   283.456390   265.701874   280.426086   273.227905  13689200.0   
2010-01-25   273.163330   266.024780   271.528961   268.255249   8897200.0   
2010-01-26   273.024231   266.412231   267.246826   269.457428   8767600.0   
2010-01-27   272.055542   265.925415   268.886169   269.298462   7980200.0   
2010-01-28   271.732635   263.585632   270.485748   265.418701   6500100.0   
2010-01-29   268.747070   261.106750   267.505127   263.257751   8334700.0   
2010-02-01   266.173798   263.436584   265.572693   264.787811   4530800.0   
2010-02-02   265.751556   262.100281   265.751556   263.843964   8245600.0   
2010-02-03   269.298462   262.408295   262.626862   268.662598   6037000.0   
2010-02-04   267.261719   261.081909   266.764954   261.687958   6799200.0   
2010-02-05   265.026245   259.541931   262.492737   263.928406   6353000.0   
2010-02-08   269.248810   264.047638   264.529480   265.011353   5423500.0   
2010-02-09   269.015320   265.806183   268.026733   266.486755   5675700.0   
2010-02-10   267.157410   262.140045   265.309418   265.498199   5383700.0   
2010-02-11   268.498688   263.039185   264.936829   266.466888   4851300.0   
2010-02-12   266.839478   263.535950   264.762970   264.837494   4589000.0   
2010-02-16   270.306915   265.423676   266.700378   268.901062   7356200.0   
...                 ...          ...          ...          ...         ...   
2018-11-01  1083.974976  1062.459961  1075.800049  1070.000000   1482000.0   
2018-11-02  1082.974976  1054.609985  1073.729980  1057.790039   1839000.0   
2018-11-05  1058.469971  1021.239990  1055.000000  1040.089966   2441400.0   
2018-11-06  1064.344971  1038.069946  1039.479980  1055.810059   1233300.0   
2018-11-07  1095.459961  1065.900024  1069.000000  1093.390015   2058400.0   
2018-11-08  1093.270020  1072.204956  1091.380005  1082.400024   1488200.0   
2018-11-09  1075.560059  1053.109985  1073.989990  1066.150024   1343200.0   
2018-11-12  1062.119995  1031.000000  1061.390015  1038.630005   1471800.0   
2018-11-13  1056.604980  1031.150024  1043.290039  1036.050049   1513700.0   
2018-11-14  1054.563965  1031.000000  1050.000000  1043.660034   1565900.0   
2018-11-15  1071.849976  1031.780029  1044.709961  1064.709961   1836100.0   
2018-11-16  1067.000000  1048.979980  1059.410034  1061.489990   1658100.0   
2018-11-19  1060.790039  1016.260010  1057.199951  1020.000000   1858600.0   
2018-11-20  1031.739990   996.020020  1000.000000  1025.760010   2449100.0   
2018-11-21  1048.560059  1033.469971  1036.760010  1037.609985   1534300.0   
2018-11-23  1037.589966  1022.398987  1030.000000  1023.880005    691500.0   
2018-11-26  1049.310059  1033.910034  1038.349976  1048.619995   1942800.0   
2018-11-27  1057.579956  1038.489990  1041.000000  1044.410034   1803200.0   
2018-11-28  1086.839966  1035.760010  104

In [280]:
#2
google[google['Adj Close'] == google['Adj Close'].max()].index[0]
# or
google['Adj Close'].idxmax()

Timestamp('2018-07-26 00:00:00')

In [281]:
#3
google[google['Adj Close'] == google['Adj Close'].min()].index[0]
# or
google['Adj Close'].idxmin()

Timestamp('2010-07-06 00:00:00')

In [282]:
#4
google['Adj Close'].mean()

580.7621749634222