### 1A: Compare tuples and list creation: is one faster than the other?

In [ ]:
import timeit

In [2]:
stmt = """\
a = ['WORDS']*1000
"""
timeit.timeit(stmt)

3.3750789630000004

In [3]:
stmt = """\
a = ('WORDS',) * 1000
"""
timeit.timeit(stmt)

3.4153811700000007

They are about the same time

### 1B: Compare tuple and list concatenation: is one faster?

In [4]:
stmt = """\
a = ['WORDS']*1000 + ['WORDS']*1000
"""
timeit.timeit(stmt)

12.720408999000002

In [5]:
stmt = """\
a = ('WORDS',) * 1000 + ('WORDS',) * 1000
"""
timeit.timeit(stmt)

13.36401961

They are about the same time too

### 1C: Compare two ways of placing a new value in a sorted list: either, by appending it to the end and then sorting, or by using insort.

In [6]:
import bisect

In [7]:
stmt = """\
a = list(range(0,1000))
a.append(25)
a.sort()
"""
timeit.timeit(stmt)

16.983399118

In [8]:
stmt = """\
a = list(range(0,1000))
bisect.insort(a,25)
"""
timeit.timeit(stmt, setup = 'import bisect')

12.917347587999998

bisect.insort is significantly faster with a list of 1000. The difference will definitely grow as the size of the list grows

# Chapter 4
## NumPy Basics: Arrays and Vectorized Computation

### 4.1 The NumPy ndarray: A Multidimensional Array Object

In [9]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.23058159,  0.16383479, -0.77201015],
       [-0.13889583,  0.8981899 , -0.07803063]])

In [10]:
data * 10

array([[ 2.30581588,  1.63834791, -7.72010149],
       [-1.3889583 ,  8.98189902, -0.78030629]])

In [11]:
data + data

array([[ 0.46116318,  0.32766958, -1.5440203 ],
       [-0.27779166,  1.7963798 , -0.15606126]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1= [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int32')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2,3,2))

array([[[1.09885297e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.77244562e+180]],

       [[1.08551929e-042, 1.53297621e-075],
        [9.39588454e+165, 3.57428419e-061],
        [5.21643993e-037, 3.38134314e-061]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [30]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [32]:
numeric_strings = np.array(['1.25','-9.6','42'])
numeric_strings.astype(np.float)

array([ 1.25, -9.6 , 42.  ])

In [34]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
empty_uint32 = np.empty(8, dtype = 'u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [36]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [42]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [43]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [45]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [50]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [51]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [52]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [53]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [54]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [55]:
arr2d[0][2]

3

In [56]:
arr2d[0,2]

3

In [57]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[1,0]

array([7, 8, 9])

In [62]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [63]:
x[0]

array([7, 8, 9])

In [64]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [65]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [66]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [70]:
arr2d[1, :2]

array([4, 5])

In [71]:
arr2d[:2,2]

array([3, 6])

In [72]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [73]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [74]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [75]:
data

array([[ 1.5398715 ,  0.09121279, -0.34606784,  1.91763788],
       [ 0.38684955, -2.27467966,  1.74904734, -0.2441826 ],
       [-1.27105318,  1.04566663,  1.09758643, -0.09527467],
       [ 0.18782271,  0.62362856,  1.83964887,  0.43878055],
       [-0.82244481,  0.28147603,  1.54133035,  0.30101437],
       [ 0.22878708, -0.04648937,  0.05939312, -0.19727054],
       [-0.5042502 ,  0.83787147,  2.23038452,  0.57310144]])

In [76]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [77]:
data[names == 'Bob']

array([[ 1.5398715 ,  0.09121279, -0.34606784,  1.91763788],
       [ 0.18782271,  0.62362856,  1.83964887,  0.43878055]])

In [78]:
data[names == 'Bob', 2:]

array([[-0.34606784,  1.91763788],
       [ 1.83964887,  0.43878055]])

In [79]:
data[names == 'Bob', 3]

array([1.91763788, 0.43878055])

In [80]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [81]:
data[~(names == 'Bob')]

array([[ 0.38684955, -2.27467966,  1.74904734, -0.2441826 ],
       [-1.27105318,  1.04566663,  1.09758643, -0.09527467],
       [-0.82244481,  0.28147603,  1.54133035,  0.30101437],
       [ 0.22878708, -0.04648937,  0.05939312, -0.19727054],
       [-0.5042502 ,  0.83787147,  2.23038452,  0.57310144]])

In [82]:
cond = names == 'Bob'
data[~cond]

array([[ 0.38684955, -2.27467966,  1.74904734, -0.2441826 ],
       [-1.27105318,  1.04566663,  1.09758643, -0.09527467],
       [-0.82244481,  0.28147603,  1.54133035,  0.30101437],
       [ 0.22878708, -0.04648937,  0.05939312, -0.19727054],
       [-0.5042502 ,  0.83787147,  2.23038452,  0.57310144]])

In [83]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [84]:
data[mask]

array([[ 1.5398715 ,  0.09121279, -0.34606784,  1.91763788],
       [-1.27105318,  1.04566663,  1.09758643, -0.09527467],
       [ 0.18782271,  0.62362856,  1.83964887,  0.43878055],
       [-0.82244481,  0.28147603,  1.54133035,  0.30101437]])

In [85]:
data[data < 0] = 0
data

array([[1.5398715 , 0.09121279, 0.        , 1.91763788],
       [0.38684955, 0.        , 1.74904734, 0.        ],
       [0.        , 1.04566663, 1.09758643, 0.        ],
       [0.18782271, 0.62362856, 1.83964887, 0.43878055],
       [0.        , 0.28147603, 1.54133035, 0.30101437],
       [0.22878708, 0.        , 0.05939312, 0.        ],
       [0.        , 0.83787147, 2.23038452, 0.57310144]])

In [86]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.38684955, 0.        , 1.74904734, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.22878708, 0.        , 0.05939312, 0.        ],
       [0.        , 0.83787147, 2.23038452, 0.57310144]])

In [87]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [88]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [89]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [90]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [91]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [92]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [93]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [95]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
arr = np.random.randn(6,3)
arr

array([[ 0.41595694,  0.91869345,  0.01199698],
       [ 0.28227963,  2.39120194, -1.39995396],
       [-2.45301471, -0.402618  , -0.3799849 ],
       [ 1.15583076, -0.76797758,  0.41367525],
       [ 0.20770784,  1.52005207, -0.36524794],
       [-1.10516559,  0.10044429,  2.10157677]])

In [97]:
np.dot(arr.T,arr)

array([[ 8.87046138,  1.36181945, -1.37839632],
       [ 1.36181945,  9.63438253, -3.84536014],
       [-1.37839632, -3.84536014,  6.82556172]])

In [98]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [100]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 4.2 Universal Functions: Fast Element-Wise Array Functions

In [102]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [104]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [105]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.76587348, -0.43400813,  0.62746936, -0.61874776,  0.2729289 ,
        0.34476188, -0.51634726,  0.68283975])

In [106]:
y

array([-0.63190161,  0.08382439, -1.72589346,  0.8123904 ,  2.00182763,
        0.88078468, -0.87056119,  0.63630926])

In [107]:
np.maximum(x,y)

array([ 0.76587348,  0.08382439,  0.62746936,  0.8123904 ,  2.00182763,
        0.88078468, -0.51634726,  0.68283975])

In [108]:
arr = np.random.randn(7) * 5
arr

array([ 0.36361237,  3.53554187, -0.55577752, -5.44026134,  5.13776598,
        3.12154334, -3.45451574])

In [110]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.36361237,  0.53554187, -0.55577752, -0.44026134,  0.13776598,
        0.12154334, -0.45451574])

In [111]:
whole_part

array([ 0.,  3., -0., -5.,  5.,  3., -3.])

In [112]:
arr

array([ 0.36361237,  3.53554187, -0.55577752, -5.44026134,  5.13776598,
        3.12154334, -3.45451574])

In [113]:
np.sqrt(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.6030028 , 1.88030367,        nan,        nan, 2.26666406,
       1.76678899,        nan])

In [114]:
np.sqrt(arr,arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.6030028 , 1.88030367,        nan,        nan, 2.26666406,
       1.76678899,        nan])

In [115]:
arr

array([0.6030028 , 1.88030367,        nan,        nan, 2.26666406,
       1.76678899,        nan])